### ISSUE TITLE
`领子多娜` -> `围巾多娜`

### ISSUE THREAD

**Issue by CCXXXI** [re0wiki/wiki-bot#210]
代 [User:Pengruiqi4374](https://rezero.fandom.com/zh/wiki/User:Pengruiqi4374) 提出，其于以下编辑尝试修改译名：

- [“角色：领子多娜” 的版本间差异 | Re: 从零开始的异世界生活 Wiki | Fandom](https://rezero.fandom.com/zh/wiki/%E8%A7%92%E8%89%B2:%E9%A2%86%E5%AD%90%E5%A4%9A%E5%A8%9C?diff=184474&oldid=184473)

**Comment by devil233-ui** [comment]
襟 没有围巾的意思

**Comment by CCXXXI** [comment]
Duplicate of #215
