### ISSUE TITLE
`艾奇多娜` -> `艾姬多娜`

### ISSUE THREAD

**Issue by ruiqi4374** [re0wiki/wiki-bot#216]
### 新译名的来源

网络
简体中文翻译

### 为什么新译名比旧译名更好？

‘姬’更便于理解
再加百度百科&萌娘百科均翻译为艾姬多娜
动画中的翻译也为艾姬多娜

**Comment by devil233-ui** [comment]
奇可以代表多娜特征之一，姬似乎没有体现
