### ISSUE TITLE
`Rodorigesu` -> `罗德利格斯`

### ISSUE THREAD

**Issue by lqian35** [re0wiki/wiki-bot#237]
### 检查重复提议

- [X] 该译名未被提出过

### 译名的来源

My fair bad lady

**Comment by CCXXXI** [comment]
发现的其他版本译名：

- 罗德里格斯
  - by [类鬼 16384](https://rezero.fandom.com/zh/wiki/User:%E7%B1%BB%E9%AC%BC16384)
  - https://rezero.fandom.com/zh/wiki/%E8%A7%92%E8%89%B2:%E8%92%82%E4%BA%9A%E6%96%AF?diff=165947&oldid=164560
