### ISSUE TITLE
`Korin` -> `柯林·拉布里尔`

### ISSUE THREAD

**Issue by lqian35** [re0wiki/wiki-bot#238]
### 检查重复提议

- [X] 该译名未被提出过

### 译名的来源

奥托的悲喜交杂行商录

**Comment by CCXXXI** [comment]
https://rezero.fandom.com/zh/wiki/角色:格林

**Comment by CCXXXI** [comment]
格林已经被グリム占用了，至少一方得换个译名

**Comment by lqian35** [comment]
叫科林或者柯林怎么样？

**Comment by CCXXXI** [comment]
> 叫科林或者柯林怎么样？

可以，确定一下要用哪个

**Comment by lqian35** [comment]
用柯林吧
