### ISSUE TITLE
`格莱特` 不应替换为 `柯蕾特`

### ISSUE THREAD

**Issue by lqian35** [re0wiki/wiki-bot#320]
### 错误替换示例

https://rezero.fandom.com/zh/wiki/MediaWiki:Wiki-navigation

### 补充说明

navigation列表还是最好不要自动替换了吧，容易导致链接失效。

**Comment by CCXXXI** [comment]
会在 navigation 出问题的替换也会在其他地方出问题，不能仅通过略过 navigation 来解决。
