### ISSUE TITLE
`小说:三傻同行！诅咒的女神像篇` -> `小说:三傻同行！诅咒的女神像（中篇）`

### ISSUE THREAD

**Issue by lqian35** [re0wiki/wiki-bot#327]
### 检查重复提议

- [X] 该译名未被提出过

### 新译名的来源

想将这个页面变成系列的中篇，再新增两个页面对应前篇和后篇。

### 为什么新译名比旧译名更好？

如上，英维已经做了相应改动。

**Comment by CCXXXI** [comment]
这不属于译名修改，直接移动页面即可。
