### ISSUE TITLE
`普莉斯卡` -> `普丽斯卡`

### ISSUE THREAD

**Issue by devil233-ui** [re0wiki/wiki-bot#98]
与相关的翻译菌讨论后小寡妇中文名还是定为了【普丽斯卡】，虽然可以的话还想把第一个字也改了，但似乎没有足够合适又显得少女的字可用。

**Comment by CCXXXI** [comment]
@devil233-ui 若说换字可以强调改名，则同字亦可强调关联性，孰优孰劣？

**Comment by devil233-ui** [comment]
于本作是前者

**Comment by devil233-ui** [comment]
> @devil233-ui 若说换字可以强调改名，则同字亦可强调关联性，孰优孰劣？
于本作是前者

**Comment by CCXXXI** [comment]
@devil233-ui 日文前两个假名是完全相同的，译名做出差异有失准确性

**Comment by devil233-ui** [comment]
声调这玩意在大部分语言里普遍存在，至少日文。

**Comment by CCXXXI** [comment]
@devil233-ui 有依据表明 プリシラ 和 プリスカ 中的 プリ 读法不同吗
